# Site
name: "The Product Management Blog"
title: "PM Blog"
description: "Welcome to the product management blog. There are many articles written on Product Management daily, and its hard to follow and subscribe to all.
We use ML models to curate a weekly summary of important product management blogs, videos and articles/interviews from Product Leaders. Subscribe and stay tuned!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'G-8PK595M6VH'
disqus: 'http-designthinkplay-com'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Vipul:
    name: Vipul
    display_name: Vipul
    avatar: 'assets/images/vipul.png'
    email: neoeahit@gmail.com
    web: 
    twitter: https://www.notion.so/thedatapm/Hi-I-am-Vipul-540689c44307478292e71e5ef1bf8943
    description: "Loves all things product"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
